name: Deploy

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: self-hosted
        environment: production

        steps:
            - uses: actions/checkout@v3
            - name: Generate .env file
              run: |
                  echo "APP_NAME=$(basename ${{ github.repository }})" >> .env
                  # Автоматически добавляем все secrets, кроме GITHUB_TOKEN
                  for secret in $(echo ${{ toJson(secrets) }} | jq -r 'to_entries[] | select(.key != "GITHUB_TOKEN") | .key'); do
                      echo "$secret=\"${{ secrets[secret] }}\"" >> .env
                  done

            - name: Build and push Docker image
              run: |
                  docker compose --env-file .env -f docker/docker-compose.$DEPLOY_MODE.yaml up -d --build
              env:
                  DEPLOY_MODE: ${{ secrets.DEPLOY_MODE }}
